### ISSUE TITLE
Reports basic structure

### ISSUE THREAD

**Issue by maldins46** [scalaquest/PPS-19-ScalaQuest#20]
Both PPS and LSS parts of the project require us a report, that should be written in Markdown. It would be useful if someone starts to create a basic structure for the reports, with a starting point in the README.md file. 

I imagine the README with a basic description of the project, maybe the initial assignment also, and at least two links, to the two different Markdown files that should be the starting point for LSS and PPS reports.

This task includes both the definition of the basic navigation structure of the README and the subdivision into chapters for each report.

**Comment by lippo97** [comment]
@francescogorini and I are planning to take care of this in the coming days.

**Comment by corinz97** [comment]
Hi guys! After some attempts i managed to use this [action](https://github.com/pandoc/pandoc-action-example) for generating a pdf-latex from a markdown file using Pandoc . This mechanism uses directly a pandoc docker image, so it's possible to use directly commands as if was used in a local installation. This means that many conversion possibilities are easily accessible. When the file is generated, it's saved as artifact. We should discuss how to make this file public in the repo. [Here](https://github.com/scalaquest/PPS-19-ScalaQuest/tree/feature/pandoc-latex) there is what has been done.

**Comment by corinz97** [comment]
I moved in forward steps: now the CI generates 2 example reports with the correct report name (one for PPS, the other for LSS). At the end of the process, it generates them as artifacts and creates a release where they are avalaible as pdf, together with source code

**Comment by francescogorini** [comment]
Today @lippo97, @corinz97 and I continued the part of CI able to create reports. 

We use pandoc and a new branch called "reports-releases". This is very helpful because when someone want to create a new release (with the pdf of the reports inside), he has to push into this one.

The solution is to use pandoc into the CI, not trought installing it in our machines because it's more correct to create the pdf version of the reports in the CI instead of locally.

Both PSS and LSS reports are divided in multiple markdown files. These files are automatically merged together to create the correct report for each parts.

To solve the problem of referencing in markdown, we use [pandoc-crossref](https://github.com/lierdakil/pandoc-crossref). If someone want to check the correct syntax, [here](https://raw.githubusercontent.com/lierdakil/pandoc-crossref/master/docs/demo/demo.md) there are some examples. Hope they are helpful!

**Comment by corinz97** [comment]
In future, a possible change could be to move the yaml reportGen file to main branch, in order to operate directly with stable versions, but activating the release generation only "by wish" (e.g. basing con commit message) and not automatically. In this way, releases will have pdf reports and stable source code.
