### ISSUE TITLE
CI optimization

### ISSUE THREAD

**Issue by maldins46** [scalaquest/PPS-19-ScalaQuest#23]
In the future, it would be nice to optimize even more the CI process. The current pipeline shares Gradle caches between jobs, to minimize eventual duplicated Gradle file generation, but not the build artifacts, that are re-created for each job.

Sharing build artifacts between jobs would minimize CI execution time. For example, using the artifact sharing action given by GitHub, or by other ways. Someone could deepen this aspect.

**Comment by corinz97** [comment]
A first optimization achieved after some attempts, in [2a83e0e](https://github.com/scalaquest/PPS-19-ScalaQuest/commit/2a83e0ec6595a5a16b823ee137c301240db4d6ca), consists in saving the buildSrc folder as artifact, and importing it in next steps after compile.

**Comment by corinz97** [comment]
I made further attempts, but when i try to artify core,cli and examples folders, something goes wrong during the check step: Gradle sub-phases about buildSrc result UP-TO-DATE, as they should, but those about the other folders are executed totally. I think this behavior is due to an [upload-artifact](https://github.com/actions/upload-artifact) aspect: it's main job it's to create artifacts, not exact copies of folders, and i've seen that some generated folders are empty, so they are not loaded on the generated artifact, Probably this is the reason why it doesn't recognize the "exact" folders presence.  Finally, compilations fails maybe due to these aspects (maybe somebody of you can help to handle this problem 👍  )
Reasoning about it, it's not a big problem to exclude these three folders, because buildSrc is the heaviest, so the workflow is faster anyway.
You can see the CI results [here](https://github.com/scalaquest/PPS-19-ScalaQuest/actions/runs/492113926).

**Comment by corinz97** [comment]
I'll try to write what i told in reunion, for clearance:

After several attempts, i decided to abandon (maybe temporarly) the solution proposed in the comment above.
The reason why is that, using github internal internet connection, for sharing artifacts, sometimes it's overloaded and few times workflow get faster, but the most of times it gets slower.

The actual workflow has three jobs , launched just on push/pull-request on main branch:

- Stylecheck
- Assemble
- Check

They are organized in an "end-to-start" fashion, so parallelism is just internal to jobs.
Just the Assemble job uses OS matrix.

Here is the first, IMHO, issue:
The Check job, which applies stylecheck, assemble and test, should run as best practice on the OS matrix, instead of just the OS Linux. This because sometimes test may fail for OS conditions.

The second point is the flow organization:
Check does also the same work of its previous jobs. So there a redundant behaviour.
In order to improve the CI speed, i suggest the following re-organization:
- Stylecheck is applied on all branches, except of main, so presumibly on every feature branch. Assemble could be also executed on those, but just on developer desire. As example, it is launched only if the commit message starts with "asm:". More complex policies could be adopted. These two jobs could be used useful during development. Here there is yaml [file](https://github.com/scalaquest/PPS-19-ScalaQuest/blob/feature/new-gradle-build/.github/workflows/not-mainbranch-stylecheck.yml)

- Check runs just on  main push/pull-request. This will give same results of actual configuration, but cutting half the time execution. Here there is yaml [file](https://github.com/scalaquest/PPS-19-ScalaQuest/blob/feature/new-gradle-build/.github/workflows/main-branch-check.yml)

**Comment by maldins46** [comment]
Perfect! Just a few observations:

> Stylecheck is applied on all branches, except of main

I think feature branches should not receive Style check **as default**, but always **upon request**. 

This because, potentially, a lot of push are performed during the feature branch life, a lot of time purposely dirty. Each time a whatever GH Action fails, an **email notification is sent to everyone**, bringing unnecessary "panic" for each personal experiment. In general, this not "scales" well (pass me the term). In short, this freedom of experimenting without too much CI checks should be the standard.
 
Anyway, giving the possibility of executing some CI with tags, to obtain the  **upon request style**, is **a great idea**. It would be useful to have two tags: one for the Style check (ex. `[style]`), and a separated one for assembling (ex. `[asm]`). It might as well be used only the `[asm]` tag, as in Gradle semantics `./gradlew assemble` is basically **assemble + styleCheck** (`spotlessCheck` task is silently executed in it).


> Check runs just on main push/pull-request

Perfect, as  `./gradlew check` basically runs **styleCheck + assemble + tests + otherChecks**. This can also be made clearer by splitting the **Check** job into more internal steps (a step for `./gradlew spotlessApply`, a step for `./gradlew assemble`, another one for `./gradlew check`). As the environment is shared into the single job, eventually duplicated tasks are not re-executed, and at the sametime, the Action output is clearer (=> easier to find eventual causes of CI fails).

**Comment by corinz97** [comment]
As suggested by @maldins46, i applied his advises and i think the results are considerably better than before.

Now Stylecheck and Assemble are invoked "upon request style" by using `[style]` and/or `[asm]` in commit message (btw assemble doesn't call spotlessCheck, so, if needed, both tags have to occur). Furthermore, they could be applied not only on feature branches, but on every kind of branch, just on push.

About check, it has been splitted as suggested and works very well.

I'm going to open the pull request.
